apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: {{ .Values.email }}
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    solvers:
      - http01:
          ingress:
            ingressClassName: istio
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.email }}
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
      - http01:
          ingress:
            ingressClassName: istio
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hello-cert
  namespace: istio-system
spec:
  secretName: hello-cert-tls
  dnsNames:
    - "hello.{{ .Values.subdomain }}"
  issuerRef:
    name: {{ .Values.acme_issuer }}
    kind: ClusterIssuer
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: hello-vs
  namespace: hello-world
spec:
  hosts:
    - "hello.{{ .Values.subdomain }}"
  gateways:
    - mesh
    - istio-system/internal-gateway
  http:
    - match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: hello-world.hello-world.svc.cluster.local
            port:
              number: 80
